name: build_node_compilers
version: 0.4.0
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  bazel_worker: ^1.0.3
  build: ^2.4.1
  build_config: ^1.1.1
  build_modules: ^5.0.4
  collection: ^1.18.0
  crypto: ^3.0.3
  logging: ^1.2.0
  meta: ^1.9.1
  node_preamble: ^2.0.2
  path: ^1.8.3
  pool: ^1.5.1
  scratch_space: ^1.0.2

dev_dependencies:
  build_test: ^2.2.0
  build_runner: ^2.4.6
  test: ^1.24.6
  a: 
    path: ./test/fixtures/a
  b: 
    path: ./test/fixtures/b
